version: 2
workflows:
  version: 2
  build:
    jobs:
      - test-python-2.7
      - test-python-3.4
      - test-python-3.5
      - test-python-3.6
      - test-python-3.7
jobs:
  test-python-2.7:  &test-python-template
    docker:
      - image: circleci/python:2.7-browsers
    working_directory: ~/facebook-sdk
    steps:
      - checkout
      - run:
          name: install virtualenv and dependencies
          command: |
            mkdir -p ~/venv
            if [ $(python -c "import platform; print(platform.python_version_tuple()[0])") == "2" ]; then
              virtualenv ~/venv;
            else
              python -m venv ~/venv;
            fi;
            . ~/venv/bin/activate
            pip install pygments
            pip install .
      - run:
          name: run linting
          command: |
            . ~/venv/bin/activate
            if [ $(python -c "import platform; print(platform.python_version()[:3])") == "3.7" ]; then
              pip install black doc8;
              black -l 79 --check examples;
              black -l 79 --check facebook;
              black -l 79 --check test;
              doc8 -q *.rst docs/*.rst;
            fi;
      - run:
          name: run automated tests
          command: |
            . ~/venv/bin/activate
            python -m test.test_facebook
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-python-3.4:
    <<: *test-python-template
    docker:
      - image: circleci/python:3.4-browsers
  test-python-3.5:
    <<: *test-python-template
    docker:
      - image: circleci/python:3.5-browsers
  test-python-3.6:
    <<: *test-python-template
    docker:
      - image: circleci/python:3.6-browsers
  test-python-3.7:
    <<: *test-python-template
    docker:
      - image: circleci/python:3.7-browsers
